#SED replaces username and password on lines 7 & 8.  Don't move these
spring:
  profiles:
    active: ${SPRING_PROFILE:dev,swagger}
  datasource:
    url: ${DATASOURCE_WORLDBANK_URL:jdbc:postgresql://192.168.56.101:5080/postgres}
    username: ${DATASOURCE_WORLDBANK_USERNAME:postgres}
    password: ${DATASOURCE_WORLDBANK_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
