--
create table if not exists category_type
(
    key                      			varchar(10) not null,
	name_en_us							text not null,
	name_ar_lb							text not null,
	description_en_us                   text not null,
	description_ar_lb                   text not null,
	active								boolean not null,
    create_user_id                      int not null,
    create_timestamp                    timestamp with time zone not null,
	constraint pk_category_type primary key(key)
);

create table if not exists category_item
(
    key                      			varchar(10) not null,
	name_en_us							text not null,
	name_ar_lb							text not null,
	description_en_us                   text not null,
	description_ar_lb                   text not null,
	category_type_key					varchar(10) not null,
	active								boolean not null,
	photo_required                      boolean not null,
    create_user_id                      int not null,
    create_timestamp                    timestamp with time zone not null,
	constraint pk_category_item primary key(key),
	constraint fk_category_item_category_type foreign key (category_type_key) references category_type (key) on delete cascade
);

create table if not exists blob
(
	id                                  int not null generated by default as identity,
	mime_type                           text null,
	file_name                           text null,
	latitude                            double precision null,
	longitude                           double precision null,
    create_user_id                      int not null,
    create_timestamp                    timestamp with time zone not null,
	constraint pk_blob primary key(id)
);

create table if not exists blob_bytes
(
	id                                  int not null,   -- this will always be the same value as blob.id
	bytes								bytea not null,
    create_user_id                      int not null,
    create_timestamp                    timestamp with time zone not null,
	constraint pk_blob_bytes primary key(id)
);

create table if not exists feedback
(
    id                                  int not null generated by default as identity,
    latitude                            double precision null,
    longitude                           double precision null,
    project_id                          int not null,
    category_item_key                   varchar(10) not null,
	comment								text null,
	gender                              char(1) null,
	age_range                           text null,
    user_type                           text null,
    user_type_other                     text null,
    first_name                          text null,
    last_name                           text null,
    address                             text null,
    phone                               text null,
    email                               text null,
    update_user_id                      int not null,
    update_timestamp                    timestamp with time zone not null,
    create_user_id                      int not null,
    create_timestamp                   	timestamp with time zone not null,
    constraint pk_feedback primary key(id),
	constraint fk_feedback_project foreign key (project_id) references project (id),
	constraint fk_feedback_category foreign key (category_item_key) references category_item (key),
	constraint check_gender check (gender in ('M', 'F'))
);

create table if not exists feedback_blob
(
    feedback_id                         int not null,
    blob_id                             int not null,
    create_user_id                      int not null,
    create_timestamp                   	timestamp with time zone not null,
    constraint pk_feedback_blob primary key(feedback_id, blob_id),
    constraint fk_feedback_blob_feedback foreign key (feedback_id) references feedback (id) on delete cascade,
    constraint fk_feedback_blob_blob foreign key (blob_id) references blob (id) on delete cascade
);

--category_type
insert into category_type(key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, create_user_id, create_timestamp)
select 'ET', 'Environmental Aspect', 'المستوى البيئي', '', '', true, 0, now() on conflict do nothing;

insert into category_type(key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, create_user_id, create_timestamp)
select 'ST', 'Social Aspect', 'المستوى الاجتماعي', '', '', true, 0, now() on conflict do nothing;

insert into category_type(key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, create_user_id, create_timestamp)
select 'PHS', 'Public Health & Safety Aspect', 'الصحة والسلامة العامة', '', '', true, 0, now() on conflict do nothing;

insert into category_type(key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, create_user_id, create_timestamp)
select 'TA', 'Traffic & Accessibility Aspect', 'حركة السير وإمكانية الوصول', '', '', true, 0, now() on conflict do nothing;

insert into category_type(key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, create_user_id, create_timestamp)
select 'OTH', 'Other Aspect (please specify)', 'موضوع أخر (الرجاء التوضيح)', '', '', true, 0, now() on conflict do nothing;

--Environmental Topic
insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'ET-LLW', 'ET', 'Leakage of liquid waste', 'تسرّب للنفايات السائلة',
'Accidental (unintended) leakage of liquid wastes (such as sewage, oil, or fuel) resulting from the use of heavy machinery and equipment',
'تسرّب عرَضي (غير مقصود) للنفايات السائلة (كالصرف الصحي أو الزيوت أو الوقود)الناتجة عن استخدام الآلات والمعدات الثقيلة',
true, true, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'ET-SWD', 'ET', 'Solid waste disposal', 'تخلص من النفايات الصلبة',
'Improper disposal of solid waste as a result of road rehabilitation works, such as plastic, paper, glass, wood, asphalt flour and landfills',
'التخلص غير السليم من النفايات الصلبة من جراء أعمال تأهيل الطريق، مثل البلاستيك والورق والزجاج، والخشب، طحين الأسفلت والردميات',
true, true, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'ET-EOP', 'ET', 'Emission of Odors and Pollutants', 'إنبعاث روائح وملوّثات',
'Odors emitted from asphalt fumes, dust, and pollutant emissions resulting from the use of heavy machinery and equipment during rehabilitation work',
'الروائح المنبعثة من أبخرة الأسفلت والغبار وانبعاثات الملوثات الناتجة عن استخدام الآلات والمعدات الثقيلة خلال أعمال التأهيل',
true, true, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'ET-O', 'ET', 'Other', 'أشياء أخرى',
'',
'',
true, true, 0, now() on conflict do nothing;

--Social Topic
insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'ST-LI', 'ST', 'Labor Influx', 'تدفق للعمال',
'An increase in the flow of workers as a result of rehabilitation work',
'زيادة تدفق العمال جراء أعمال التأهيل',
true, false, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'ST-SH', 'ST', 'Sexual Harassment', 'وجود سلوكيات',
'The presence of unwanted sexual behavior among the workers during the rehabilitation work',
'وجود سلوك جنسي غير مرغوب فيه عند العمال خلال أعمال التأهيل',
true, false, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'ST-CL', 'ST', 'Child Labor', 'تشغيل الاطفال',
'The presence of child labor within the rehabilitation work',
'وجود عمالة الاطفال ضمن أعمال التأهيل',
true, true, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'ST-O', 'ST', 'Other', 'أشياء أخرى',
'',
'',
true, true, 0, now() on conflict do nothing;

--Public Health & Safety
insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'PHS-EN', 'PHS', 'Exposure to Noise', 'تعرّض لضجيج',
'Generation of high levels of noise and vibration resulting from rehabilitation work',
'تعرض لوقت طويل لمستويات عالية جدّاً من الضجيج والاهتزاز الناتجة عن أعمال التأهيل',
true, false, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'PHS-LCVP', 'PHS', 'Lack of Corona Virus Precautions', 'عدم الوقاية من جائحة كورونا',
'Noncompliance with the general preventive measures for protection from the Corona virus during rehabilitation work',
'عدم التقيد بالشروط الوقائية العامة للحماية من جائحة كورونا خلال أعمال التأهيل',
true, true, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'PHS-LPE', 'PHS', 'Lack of Protective Equipment', 'عدم وجود معدات حماية',
'Non-compliance with health and public safety measures (protective equipment) during rehabilitation works',
'عدم التقيد بشروط الصحة والسلامة العامة (معدات الحماية) خلال أعمال التأهيل',
true, true, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'PHS-O', 'PHS', 'Other', 'أشياء أخرى',
'',
'',
true, true, 0, now() on conflict do nothing;

-- Traffic & Accessibility
insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'TA-ITT', 'TA', 'Increased Travel Time', 'زيادة وقت التنقل',
'Increased mobility time due to rehabilitation work in the region',
'زيادة وقت التنقل بسبب أعمال التأهيل في المنطقة',
true, false, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'TA-RB', 'TA', 'Road Blockage', 'قطع طريق',
'Road blockage and negatively impacting traffic in the area as a result of rehabilitation work',
'قطع طريق والتأثير السلبي على حركة المرور في المنطقة جراء أعمال التأهيل',
true, true, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'TA-TJ', 'TA', 'Traffic Jams', 'إزدحام سير',
'Traffic jams as a result of rehabilitation work',
'الازدحام المروري بسبب أعمال التأهيل في المنطقة',
true, true, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'TA-TP', 'TA', 'Traffic Problem, Entry and Exit', 'مشكلة مرور، دخول وخروج',
'Obstructing passage and entry routes as a result of rehabilitation work in the area',
'إعاقة طرق المرور والدخول جراء أعمال التأهيل في المنطقة',
true, true, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'TA-ATL', 'TA', 'Absence of Traffic Lights', 'عدم وجود إشارات مرورية',
'Absence of appropriate traffic signs, signals and barriers during rehabilitation work',
'عدم استخدام اللافتات والاشارات المرورية المناسبة خلال أعمال التأهيل',
true, true, 0, now() on conflict do nothing;

insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'TA-O', 'TA', 'Other', 'أشياء أخرى',
'',
'',
true, true, 0, now() on conflict do nothing;

-- Other
insert into category_item(key, category_type_key, name_en_us, name_ar_lb, description_en_us, description_ar_lb, active, photo_required, create_user_id, create_timestamp)
select 'OTH-O', 'OTH', 'Other', 'أشياء أخرى',
'',
'',
true, true, 0, now() on conflict do nothing;