--
create table if not exists contact
(
    id                                  int not null generated by default as identity,
    first_name                          text null,
    last_name                           text null,
    role                                text not null,
    email                               text not null,
    update_user_id                      int not null,
    update_timestamp                    timestamp with time zone not null,
    create_user_id                      int not null,
    create_timestamp                   	timestamp with time zone not null,
    constraint pk_contact primary key (id),
    constraint uk_email unique (email)
);

create table if not exists feedback_contact
(
    feedback_id	                       int not null,
    contact_id                         int not null,
    create_user_id                      int not null,
    create_timestamp                   timestamp with time zone not null default now(),
    constraint pk_feedback_contact primary key (feedback_id, contact_id),
    constraint fk_feedback_contact_feedback foreign key (feedback_id) references feedback (id) on delete cascade,
    constraint fk_feedback_contact_contact foreign key (contact_id) references contact (id) on delete cascade
);

create table if not exists contact_kadaa
(
    contact_id                          int not null,
    kadaa_key                           varchar(10) not null,
    create_user_id                      int not null,
    create_timestamp                   	timestamp with time zone not null,
    constraint pk_contact_kadaa primary key (contact_id, kadaa_key),
    constraint fk_contact_kadaa_contact foreign key (contact_id) references contact (id) on delete cascade,
    constraint fk_contact_kadaa_kadaa foreign key (kadaa_key) references kadaa (key) on delete cascade
);